"""
Build script for the static doc site.

Walks every .md file in the repo and bundles them into `site_data.js` so
`index.html` can render them WITHOUT a local server (works from file://).

Usage:
    python build_site.py

Run it once to generate site_data.js. Re-run any time you edit or add
markdown files. No third-party dependencies.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent.resolve()

# Skip generated / vendor / hidden trees so we don't bundle noise.
SKIP_DIRS = {
    ".venv",
    "venv",
    "env",
    "node_modules",
    ".next",
    "dist",
    "build",
    ".git",
    ".idea",
    ".vscode",
    "__pycache__",
    ".dist",
    ".ipynb_checkpoints",
}


def should_skip(path: Path) -> bool:
    return any(part in SKIP_DIRS for part in path.parts)


def collect() -> dict[str, str]:
    files: dict[str, str] = {}
    for md_path in ROOT.rglob("*.md"):
        rel = md_path.relative_to(ROOT)
        if should_skip(rel):
            continue
        # Normalize to forward slashes — that's how the SPA routes work.
        key = rel.as_posix()
        try:
            files[key] = md_path.read_text(encoding="utf-8")
        except Exception as exc:
            print(f"  ⚠️  skipped {key}: {exc}")
    return files


def main() -> int:
    files = collect()
    out_path = ROOT / "site_data.js"
    payload = json.dumps(files, ensure_ascii=False)
    out_path.write_text(
        f"// Auto-generated by build_site.py — do not edit by hand.\n"
        f"window.FILES = {payload};\n",
        encoding="utf-8",
    )
    print(f"✅ Wrote {out_path.name} with {len(files)} markdown file(s).")
    print("   Open index.html directly in your browser to view the site.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
